name: tms-web-isolation

on:
  push:
    branches:
      - isolation
permissions:
  contents: write  # Give the GITHUB_TOKEN permission to push tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitLab Container Registry
      - name: Log in to GitLab Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_ACCESS_TOKEN }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-files
          path: docker-compose.yml

      # Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build . -t registry.gitlab.com/armuro.rey.dev/container-registry/jos-tms-web-isolation:${{ github.sha }}
          docker push registry.gitlab.com/armuro.rey.dev/container-registry/jos-tms-web-isolation:${{ github.sha }}
      # Create a new tag and push it to GitHub
      - name: Create and push Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          TAG="${{ github.ref_name }}-${{ github.sha }}"
          echo "Creating Git tag $TAG"
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Set up SSH key
      # - name: Set up SSH agent
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     password: ${{ secrets.LIGHTSAIL_SSH_KEY_ISO }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-files

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to AWS Lightsail
        run: |
          PASS=$(echo "${{ secrets.LIGHTSAIL_SSH_KEY_ISO }}" | base64 -d)

          echo "Starting deploy to Lightsail host..."
          echo "Host: ${{ secrets.LIGHTSAIL_HOST_ISO }}"
          echo "User: ${{ secrets.LIGHTSAIL_USER_ISO }}"

          sshpass -p "$PASS" scp -o StrictHostKeyChecking=no docker-compose.yml \
            ${{ secrets.LIGHTSAIL_USER_ISO }}@${{ secrets.LIGHTSAIL_HOST_ISO }}:/root/jos-tms-web-iso/docker-compose.yml

          sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.LIGHTSAIL_USER_ISO }}@${{ secrets.LIGHTSAIL_HOST_ISO }} << 'EOF'
          set -e
          cd /root/jos-tms-web-iso

          echo "TAG=${{ github.sha }}" > .env
          echo 'VITE_FRONT_API=${{ vars.VITE_FRONT_API_ISO }}' >> .env
          echo 'VITE_GOOGLE_API=${{ vars.VITE_GOOGLE_API_ISO }}' >> .env

          echo "Logging in to GitLab Container Registry"
          docker login -u ${{ secrets.GITLAB_USERNAME }} -p ${{ secrets.GITLAB_ACCESS_TOKEN }} registry.gitlab.com

          echo "Rebuilding containers..."
          docker-compose down
          docker-compose up -d

          echo "âœ… Deploy completed successfully."
          EOF
